CC = gcc
TARGET = SimpsonRule.out
OBJS = SimpsonRule.o
SRCS = SimpsonRule.c

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS) -lm

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(OBJS)
	rm $(TARGET)
